### ISSUE TITLE
Preserve xml comments in config.xml

### ISSUE THREAD

**Issue by mspace** [SamVerschueren/gulp-cordova-version#5]
I'm using this plugin to update version xml attribute of existing config.xml:

``` javascript
gulp.task("update-version-xml-continous-integration", function () {

  console.log("1. Task: update-version-xml-continous-integration");

  var v = process.env.CCNetLabel;
  if( typeof v === "undefined" ) {
    console.log("Could not retrieve CCNetLabel environment variable");
    process.exit(1);
  }
  return gulp.src('.').pipe(version(v)); // . points to root of Cordova project
});
```

Is there a way to preserve xml comments . Currently when task finishes, it removes all comments from config.xml file.

**Comment by SamVerschueren** [comment]
This extension uses [cordova-config](https://github.com/SamVerschueren/cordova-config) in the background which parses the XML to easily manipulate the tree elements and then it writes the config file again.

Why do you need comments in your `config.xml`? The file is automatically generated and I don't think it should be touched by the user at all.

**Comment by mspace** [comment]
I'm using Microsoft Visual Studio which generates config.xml. It adds comments like this:

``` xml
 <platform name="ios">
    <!-- iOS 8.0+ -->
    <!-- iPhone 6 Plus  -->
    <icon src="res/icons/ios/icon-60-3x.png" width="180" height="180" />
    <!-- iOS 7.0+ -->
    <!-- iPhone / iPod Touch  -->
    <icon src="res/icons/ios/icon-60.png" width="60" height="60" />
    <icon src="res/icons/ios/icon-60-2x.png" width="120" height="120" />
    <!-- iPad -->
    <icon src="res/icons/ios/icon-76.png" width="76" height="76" />
    <icon src="res/icons/ios/icon-76-2x.png" width="152" height="152" />
    <!-- iOS 6.1 -->
    <!-- Spotlight Icon -->
    <icon src="res/icons/ios/icon-40.png" width="40" height="40" />
    <icon src="res/icons/ios/icon-40-2x.png" width="80" height="80" />
    <!-- iPhone / iPod Touch -->
    <icon src="res/icons/ios/icon-57.png" width="57" height="57" />
    <icon src="res/icons/ios/icon-57-2x.png" width="114" height="114" />
    <!-- iPad -->
    <icon src="res/icons/ios/icon-72.png" width="72" height="72" />
    <icon src="res/icons/ios/icon-72-2x.png" width="144" height="144" />
    <!-- iPhone Spotlight and Settings Icon -->
    <icon src="res/icons/ios/icon-small.png" width="29" height="29" />
    <icon src="res/icons/ios/icon-small-2x.png" width="58" height="58" />
    <!-- iPad Spotlight and Settings Icon -->
    <icon src="res/icons/ios/icon-50.png" width="50" height="50" />
    <icon src="res/icons/ios/icon-50-2x.png" width="100" height="100" />
```

**Comment by SamVerschueren** [comment]
Don't think I am able to preserve the comments as [elementtree](https://github.com/racker/node-elementtree) does not allow me to.

> I'm using Microsoft Visual Studio which generates config.xml.

I have no experience with that approach, I use all the [gulp-cordova](https://github.com/SamVerschueren/gulp-cordova) plugins to automatically generate my `config.xml` and I never read or touch the config file.

---

If you want to keep the comments, you could create your own gulp plugin which adds the version to the widget tag with a regex instead of parsing the entire dom tree. Another approach would be to create an issue in `elementtree` and ask if they could preserve comments when parsing. This one is out of my hands I'm afraid.

Feel free to provide feedback :).
